from snakemake.io import glob_wildcards

include: "rules/trim_reads.smk"
include: "rules/spades.smk"
include: "rules/prokka.smk"
include: "rules/gtdbtk.smk"
include: "rules/gtotree.smk"
include: "rules/multi_prokka.smk"
include: "rules/gffs.smk"
include: "rules/roary.smk"

OUTPUT = config["output"]
TREE = config["tree_type"]
RULE_TYPE = config["rule_type"]

#pre-determined entries for rule all depending on which snakemake call it is
RULE_ALL_DICT = {
    "isolate": [f"{OUTPUT}/isolate_prokka/genome_isolate.gff", f"{OUTPUT}/gtdbtk/gtdbtk.bac120.summary.tsv"],
    "gtotree": [f"{OUTPUT}/{TREE}_tree/{TREE}_tree.tre"]
}

#create wildcards to pull the unzipped .fa accessions into prokka rule to run in parallel
if RULE_TYPE == "pangenome":
    SAMPLES, = glob_wildcards(f"{OUTPUT}/fasta/{{sample}}.fa")
    RULE_ALL = [f"{OUTPUT}/roary/gene_presence_absence.csv"]

#select the rule depending on what config file variable is set as
else: 
    RULE_ALL = RULE_ALL_DICT[RULE_TYPE]

rule all:
    input:
        RULE_ALL